Models/ActivityModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCMyFirst.Models
{
    public class ActivityModel
    {
        public string name { get; set; }
        public int hoursSpent { get; set; }
        public bool spreadable { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMyFirst.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMyFirst.Controllers
{
    public class MyController : Controller
    {
        
        // GET: My
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string selection)
        {
            var selectedItem = HttpUtility.HtmlEncode(selection);
            var viewName = "";
            switch (selectedItem)
            {
                case "Kiteboarding":
                    viewName = "Kiteboarding";
                    break;
                case "Jogging":
                    viewName = "Jogging";
                    break;
                case "Coding":
                    viewName = "Coding";
                    break;
                default:
                    viewName = "Index";
                    break;
            }
            return View(viewName);
        }

        public ActionResult YourFavForm()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YourFavForm(string name, bool shareable, int hours)
        {
            if (name == "")
            {
                ViewBag.message = "You forgot to type in the activity name, but thank you for taking the time to share.";
            }
            else if (shareable && name != "")
            {
                ViewBag.message = "Thank you for informing me about " + name;
                if (hours < 50)
                {
                    ViewBag.message += ". It sounds like your just getting started in this activity.  I hope you keep enjoying " + name + ".";
                }
                else
                {
                    ViewBag.message += ". It sounds like you have been doing it a while.";
                }
            }
            else
            {
                ViewBag.message = "Thank you for filling out the form.  I won't share your favortie activity.";
            }
            return View("ThankYou");
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>This site was created for fun.  If you find it fun share it with someone!</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    555 Fun Rd.<br />
    Traverse City, MI 49686<br />
    <abbr title="Phone">P:</abbr>
    231-555-1234
</address>

<address>
    <strong>Email:</strong>   <a href="mailto:Support@example.com">Support@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>This is my first MVC application using ASP.NET</h1>
    <p class="lead">Here you will find random things that i enjoy</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Kite Boarding</h2>
       <img src="~/Content/kite.jpg" style="width:50%;" />
    </div>
    <div class="col-md-4">
        <h2>Coding</h2>
        <img src="~/Content/code.jpg" style="width:50%;"/>
    </div>
    <div class="col-md-4">
        <h2>Jogging</h2>
        <img src="~/Content/jogging.jpg" style="width:50%;"/>
    </div>
</div>

Views/My/Coding.cshtml
@{
    ViewBag.Title = "Coding";
}

<h2>Coding</h2>

Views/My/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Which one of my favorite activities would you like to learn more about?</h2>
<form name="activities" method="post">
    <select name="selection">
        <option name="Kiteboarding">Kiteboarding</option>
        <option name="Jogging">Jogging</option>
        <option name="Coding">Coding</option>
    </select>
    <button type="submit">Submit</button>
</form>

Views/My/Jogging.cshtml
@{
    ViewBag.Title = "Jogging";
}

<h2>Jogging</h2>

Views/My/Kiteboarding.cshtml
@{
    ViewBag.Title = "Kiteboarding";
}

<h2>Kiteboarding</h2>

Views/My/ThankYou.cshtml
@{
    ViewBag.Title = "ThankYou";
}

<h2>ThankYou</h2>
@ViewBag.Message

Views/My/YourFavForm.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tell Me About Your Favorite</title>
    @Styles.Render("~/Content/Favorite.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <header>
        <h2>Whats Favorite Activity</h2>
    </header>
    <form name="favorite" method="post">
        
        <p>Activity Name: <input type="text" name="name" id="name" /></p>
        <p>Hours of engagemnt:<input type="text" value="50" name="hours" id="hours" />
        <p>
           Do you mind sharing with other people:
            <select name="shareable">
                <option value="true">true</option>
                <option value="false">false</option>
            </select>
            <button type="submit">Submit</button>
        </p>
    </form>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            padding-top: 0px;
        }

        .navbar a:link {
            color: white;
        }

        .navbar a:visited {
            color: silver;
        }

        .navbar a:hover {
            color: cadetblue;
            text-shadow: 1px 1px white;
            transition: 1s;
            text-decoration: none;
            font-size: 1.2em;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" href="#">MVC MY FIRST</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Home", "Index", "Home")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("About", "About", "Home")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Contact", "Contact", "Home")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("MY Favs", "Index", "My")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Your Fav", "YourFavForm", "My")
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>